#%RAML 1.0 DataType

        type: array
        items:
            type: object
            properties:
              firstName: 
                type: string
                required: false
              lastName:
                type: string
                required: false
              dob:
                type: string
                required: false
              mobileNumber:
                type: string
                required: false
              email:
                type: string
                required: false
              address:
                type: string
                required: false
              city:  
                type: string
                required: false
              state:
                type: string
                required: false
              pincode:
                type: string
                required: false