#%RAML 1.0 NamedExample

[
                    {
                      "firstName" : "ABC",
                      "lastName" : "XYZ",
                      "dob" : "10-10-1999",
                      "mobileNumber" : "8970097666",
                      "email" :  "abc@gmail.com",
                      "address" : "abc colony, HSR Layout, Bangalore",
                      "city" : "BNGLR",
                      "state" : "KA",
                      "pincode" : "560027"}]